const Map<String, dynamic> metroDbRoute = {
  "G": {
    "G01": ["新店站", "Xindian"],
    "G01A": ["小碧潭站", "Xiaobitan"],
    "G02": ["新店區公所站", "Xindian District Office"],
    "G03": ["七張站", "Qizhang"],
    "G04": ["大坪林站", "Dapinglin"],
    "G05": ["景美站", "Jingmei"],
    "G06": ["萬隆站", "Wanlong"],
    "G07": ["公館站", "Gongguan"],
    "G08": ["台電大樓站", "Taipower Building"],
    "G09": ["古亭站", "Guting"],
    "G10": ["中正紀念堂站", "Chiang Kai-Shek Memorial Hall"],
    "G11": ["小南門站", "Xiaonanmen"],
    "G12": ["西門站", "Ximen"],
    "G13": ["北門站", "Beimen"],
    "G14": ["中山站", "Zhongshan"],
    "G15": ["松江南京站", "Songliang Nanjing"],
    "G16": ["南京復興站", "Nanjing Fuxing"],
    "G17": ["台北小巨蛋站", "Taipei Arena"],
    "G18": ["南京三民站", "Nanjing Sanmin"],
    "G19": ["松山站", "Songshan"],
  },
  "O": {
    "O01": ["南勢角站", "Nanshijiao"],
    "O02": ["景安站", "Jingan"],
    "O03": ["永安市場站", "Yongan Market"],
    "O04": ["頂溪站", "Dingxi"],
    "O05": ["古亭站", "Guting"],
    "O07": ["忠孝新生站", "Zhongxiao Xinsheng"],
    "O08": ["松江南京站", "Songliang Nanjing"],
    "O09": ["行天宮站", "Xingtian Temple"],
    "O10": ["中山國小站", "Zhongshan Elementary School"],
    "O11": ["民權西路站", "Minzuan W. Rd."],
    "O12": ["大橋頭站", "Daqiaotou"],
    "O13": ["台北橋站", "Taipei Bridge"],
    "O14": ["菜寮站", "Cailiao"],
    "O15": ["三重站", "Sanchong"],
    "O16": ["先嗇宮站", "Xianse Temple"],
    "O17": ["頭前庄站", "Touqianzhuang"],
    "O18": ["新莊站", "Xinzhuang"],
    "O19": ["輔大站", "Fu Jen University"],
    "O20": ["丹鳳站", "Danfeng"],
    "O21": ["迴龍站", "Huilong"],
    "O50": ["三重國小站", "Sanchong Elementary School"],
    "O51": ["三和國中站", "Sanhe Junior High School"],
    "O52": ["徐匯中學站", "St.lgnatius High School"],
    "O53": ["三民高中站", "Sanmin Senior High School"],
    "O54": ["蘆洲站", "Luzhou"],
  },
  "Y": {
    "Y08": ["十四張站", "Shisizhang"],
    "Y09": ["秀朗橋站", "Xiulang Bridge"],
    "Y10": ["景平站", "Jingping"],
    "Y12": ["中和站", "Zhonghe"],
    "Y13": ["橋和站", "Qiaohe"],
    "Y14": ["中原站", "Zhongyuan"],
    "Y15": ["板新站", "Banxin"],
    "Y16": ["板橋(環狀線)站", "Banqiao (Bannan Line)"],
    "Y17": ["新埔民生站", "Xinpu Minsheng"],
    "Y19": ["幸福站", "Xingfu"],
    "Y20": ["新北產業園區站", "New Taiepei Industrail Park"],
  },
  "B": {
    "BL01": ["頂埔站", "Dingpu"],
    "BL02": ["永寧站", "Yongning"],
    "BL03": ["土城站", "Tucheng"],
    "BL04": ["海山站", "Haishan"],
    "BL05": ["亞東醫院站", "Far Eastern Hospital"],
    "BL06": ["府中站", "Fuzhong"],
    "BL07": ["板橋(板南線)站", "Banqiao (Circular Line)"],
    "BL08": ["新埔站", "Xinpu"],
    "BL09": ["江子翠站", "Jiangzicui"],
    "BL10": ["龍山寺站", "Longshan Temple"],
    "BL11": ["西門站", "Ximen"],
    "BL12": ["台北車站", "Taipei Main Station"],
    "BL13": ["善導寺站", "Shandao Temple"],
    "BL14": ["忠孝新生站", "Zhongxiao Xinsheng"],
    "BL15": ["忠孝復興站", "Zhongxiao Fuxing"],
    "BL16": ["忠孝敦化站", "Xhongxiao Dunhua"],
    "BL17": ["國父紀念館站", "Sun Yat-Sen Memorial Hall"],
    "BL18": ["市政府站", "Taipei City Hall"],
    "BL19": ["永春站", "Yongchun"],
    "BL20": ["後山埤站", "Houshanpi"],
    "BL21": ["昆陽站", "Kunyang"],
    "BL22": ["南港站", "Nangang"],
    "BL23": ["南港展覽館站", "Taipei Nangang Exhibition Center"],
    "BR01": ["動物園站", "Taipei Zoo"],
    "BR02": ["木柵站", "Muzha"],
    "BR03": ["萬芳社區站", "Wanfang Community"],
    "BR04": ["萬芳醫院站", "Wanfang Hospital"],
    "BR05": ["辛亥站", "Xinhai"],
    "BR06": ["麟光站", "Linguang"],
    "BR07": ["六張犁站", "Liuzhangli"],
    "BR08": ["科技大樓站", "Technology Building"],
    "BR09": ["大安站", "Daan"],
    "BR10": ["忠孝復興站", "Zhongxiao Fuxing"],
    "BR11": ["南京復興站", "Nanjing Fuxing"],
    "BR12": ["中山國中站", "Zhongshan Junior High School"],
    "BR13": ["松山機場站", "Songshan Airport"],
    "BR14": ["大直站", "Dazhi"],
    "BR15": ["劍南路站", "Jiannan Rd."],
    "BR16": ["西湖站", "Xihu"],
    "BR17": ["港墘站", "Gangqian"],
    "BR18": ["文德站", "Wende"],
    "BR19": ["內湖站", "Neihu"],
    "BR20": ["大湖公園站", "Dahu Park"],
    "BR21": ["葫洲站", "Huzhou"],
    "BR22": ["東湖站", "Donghu"],
    "BR23": ["南港軟體園區站", "Nangang Software Park"],
  },
  "R": {
    "R02": ["象山站", "Xiangshan"],
    "R03": ["台北101/世貿站", "Taipei 101/World Trade Center"],
    "R04": ["信義安和站", "Xinyi Anhe"],
    "R05": ["大安站", "Daan"],
    "R06": ["大安森林公園站", "Daan Park"],
    "R07": ["東門站", "Dongmen"],
    "R08": ["中正紀念堂站", "Chiang Kai-Shek Memorial Hall"],
    "R09": ["台大醫院站", "NTU Hospital"],
    "R10": ["台北車站", "Taipei Main Station"],
    "R11": ["中山站", "Zhongshan"],
    "R12": ["雙連站", "Shuanglian"],
    "R13": ["民權西路站", "Minzuan W. Rd."],
    "R14": ["圓山站", "Yuanshan"],
    "R15": ["劍潭站", "Jiantan"],
    "R16": ["士林站", "Shilin"],
    "R17": ["芝山站", "Zhishan"],
    "R18": ["明德站", "Mingde"],
    "R19": ["石牌站", "Shipai"],
    "R20": ["唭哩岸站", "Qilian"],
    "R21": ["奇岩站", "Qiyan"],
    "R22": ["北投站", "Beitou"],
    "R22A": ["新北投站", "Xinbeitou"],
    "R23": ["復興崗站", "Fuxinggang"],
    "R24": ["忠義站", "Zhongyi"],
    "R25": ["關渡站", "Guandu"],
    "R26": ["竹圍站", "Zhuwei"],
    "R27": ["紅樹林站", "Hongshulin"],
    "R28": ["淡水站", "Tamsui"],
  },
};